"""task dates

Revision ID: 17df84b3ba7e
Revises: 8187537118a5
Create Date: 2025-03-27 08:18:00.153555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17df84b3ba7e'
down_revision = '8187537118a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
