"""add category to task attributes

Revision ID: 8187537118a5
Revises: f62f00cb8027
Create Date: 2025-02-13 07:43:04.470533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8187537118a5'
down_revision = 'f62f00cb8027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
